tuono-labs/tuono-documentation

- package.json
- pnpm-lock.yaml
- Supersedes #15
- Supersedes #16
Update dev dependencies
> chore(deps): update devdependencies

- src/routes/documentation/contributing/local-development.mdx
- src/routes/documentation/contributing/pull-requests.mdx
- fixes #6
- fixes #21 
As per description
I also added the "E2E test" section.
> feat: rewrite “Validate your changes” grouping by source type rather than check type

- src/routes/documentation/server-utilities/request.mdx
Fixes #9
Adds documentation for the `body` method.
> feat: add request body docs

- .github/workflows/deploy.yml
- Cargo.toml
- package.json
- pnpm-lock.yaml
Fixes None
Superseds #35
Updates tuono
> chore: update to tuono v0.17.10

- src/routes/documentation/configuration.mdx
Fixes None
Tuono PR: https://github.com/tuono-labs/tuono/pull/582
> feat(configuration): add `server.origin`

- CONTRIBUTING.md
- README.md
Fixes None
Add new "Creating a Pull Request" into CONTRIBUTING.md file
> docs(CONTRIBUTING): add information about creating PRs

- .env.development
- .env.local
- .gitignore
Fixes none
This file (.env.local) should not be committed to git. All local env files should be ignored.
This PR is unrelated to current work on env feature.
> chore: remove and ignore local env files

- eslint.config.js
- package.json
- pnpm-lock.yaml
> chore(deps): update dependency eslint-plugin-react-hooks to v5.2.0

- src/routes/documentation/tutorial/dynamic-routes.mdx
Part of #42 
The aim of this PR is improving the readability of the [Dynamic routes tutorial page](https://tuono.dev/documentation/tutorial/dynamic-routes) with improvements to the text of the page.
A code snippet was improved to remove an unnecessary Fragment.
> feat(tutorial/dynamic-routes): improve text and snippets

- README.md
> chore(README): add notice about documentation revamp (#60)

- .github/workflows/ci.yml
Fixes None
Trigger "CI" workflow on every push on `feature/documentation-revamp`  branch
> ci: add CI trigger on `feature/documentation-revamp`

- src/routes/documentation/rendering/server-side-rendering.mdx
- src/routes/documentation/tutorial/api-fetching.mdx
- src/routes/documentation/tutorial/dynamic-routes.mdx
- src/routes/documentation/tutorial/seo.mdx
Fixes #58
Related `tuono` PR:
- https://github.com/tuono-labs/tuono/pull/648
> feat: update `TuonoRouteProps` references

- Cargo.toml
- package.json
- pnpm-lock.yaml
- src/routes/__layout.tsx
- src/styles/global.scss
> chore: update tuono v to v0.19.0 + add SCSS

- src/components/ContentManager/ContentManagerContext.tsx
- src/components/ContentManager/Context.tsx
- src/routes/tutorial/__layout.tsx
- src/routes/tutorial/index.mdx
- src/routes/tutorial/intro.mdx
Fixes #67
Creating here `ContentManagerContext` in order to easily manage the `sidebar`/ `footer navigation`/`breadcrumb`/`documentation root pages` of the documentation and tutorial
> feat: create ContentManagerContext

- package.json
- pnpm-lock.yaml
- src/styles/global.scss
Fixes #72
This PR adds [modern-normalize.css](https://github.com/sindresorhus/modern-normalize) to the documentation.
> feat: add modern-normalize.css

- src/styles/_breakpoints.scss
- src/styles/_media-queries.scss
> feat: add media query mixins

- src/styles/_colors.scss
Fixes #77 
Create css colors variables for the documentation.
> feat: add colors css variables

- src/routes/docs/routing/defining-routes.mdx
Fixes None
Same as #79 on `documentation/revamp`
> feat: add `TuonoLayoutProps` (documentation/revamp)

- src/routes/documentation/routing/defining-routes.mdx
Fixes #71
- https://github.com/tuono-labs/tuono/pull/702
> feat: add `TuonoLayoutProps`

- package.json
- pnpm-lock.yaml
- src/components/App/App.tsx
- src/components/ThemeSwitch/ThemeSwitch.tsx
- src/components/ThemeSwitch/index.ts
- src/components/ThemeSwitch/theme-switch.module.scss
- src/routes/__layout.tsx
- src/styles/global.scss
Fixes #78 
Create the theme switcher logic and add theme colors.
> feat: create theme switcher logic

- src/components/ThemeSwitch/ThemeSwitch.tsx
- src/components/ThemeSwitch/theme-switch.module.scss
Fixes None
Just turning the `ThemeSwitch` component a `react-aria-component` for leveraging basic accessibility
> refactor: turn ThemeSwitch react-aria-component

- Cargo.toml
- package.json
- pnpm-lock.yaml
- src/components/Sidebar/sidebarElements.ts
- src/routes/__layout.tsx
- src/routes/documentation/__layout.tsx
- src/routes/documentation/integrations/typescript.mdx
- tuono.config.ts
Fixes None
Implement the documentation page for [this](https://github.com/tuono-labs/tuono/issues/463) feature
> feat: automatic type generation

- src/routes/documentation/server-utilities/request.mdx
Fixes none
Docs - form_data method into Request server utility
This change is related to https://github.com/tuono-labs/tuono/pull/651
> feat: Add form data method into request server util 
